import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import { Navbar } from "@/components/navbar";
import { Container } from "@/components/container";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Container classname="p:4 md:pt-12 md:pb-10 min-h-screen prose">
      {children}
    </Container>
  );
}
